env:
  UNSYMLINK_DIR: bazel-bin-unsymlink
  VERSION_NODEJS: 16.16.0
jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        architecture: x64
        distribution: zulu
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      name: Checkout Current closure-compiler Commit
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: bazelbuild/setup-bazelisk@v2
    - continue-on-error: true
      name: Build and Test
      run: bazelisk test //:all
    - continue-on-error: true
      name: Unsymlink Bazel Artifacts
      run: 'mkdir -p ${{ env.UNSYMLINK_DIR }}

        cp -t ${{ env.UNSYMLINK_DIR }} bazel-bin/compiler_uberjar_deploy.jar

        cp -t ${{ env.UNSYMLINK_DIR }} bazel-bin/*_bundle.jar

        '
    - continue-on-error: true
      name: Share Unshaded Compiler
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: unshaded_compiler
        path: ${{ env.UNSYMLINK_DIR }}/compiler_uberjar_deploy.jar
    - continue-on-error: true
      if: ${{ github.event_name == 'schedule' }}
      name: Share Snapshot Bundles
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: snapshot_bundles
        path: ${{ env.UNSYMLINK_DIR }}/*_bundle.jar
  deploy-snapshots:
    if: ${{ github.event_name == 'schedule' }}
    name: Deploy Snapshot Bundles to Sonatype
    needs:
    - build-and-test
    - test-closure-compiler-npm
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        architecture: x64
        distribution: zulu
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      name: Checkout Current closure-compiler Commit
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.VERSION_NODEJS }}
    - continue-on-error: true
      name: Grab Snapshot Bundles
      uses: actions/download-artifact@v4
      with:
        name: snapshot_bundles
        path: bazel-bin
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: closure-compiler
      name: Deploy Snapshot Bundles to Sonatype
      run: .github/ci_support/deploy_sonatype_snapshot_bundles.js
  test-closure-compiler-npm:
    name: Make Sure closure-compiler-npm is Compatible with this Compiler Build
    needs:
    - build-and-test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.VERSION_NODEJS }}
    - continue-on-error: true
      name: Checkout Current closure-compiler-npm Commit
      uses: actions/checkout@v4
      with:
        ref: master
        repository: google/closure-compiler-npm
    - continue-on-error: true
      name: Checkout Current closure-compiler Commit
      uses: actions/checkout@v4
      with:
        path: compiler
    - continue-on-error: true
      name: Grab Unshaded Compiler
      uses: actions/download-artifact@v4
      with:
        name: unshaded_compiler
        path: compiler/bazel-bin
    - continue-on-error: true
      name: Test closure-compiler-npm
      run: compiler/.github/ci_support/test_closure-compiler-npm.sh compiler/bazel-bin/compiler_uberjar_deploy.jar
name: Compiler CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
permissions:
  contents: read
